name: CI

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: -Xmx3200m
      CC_TEST_REPORTER_ID: 4c45cf8b47a2ab0a5ae149b266e533747e8c3330aa3f5e7d2898d460c6d11562
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: jars-{{ hashFiles('build.gradle.kts') }}-{{ hashFiles('app/build.gradle.kts') }}
      - name: Lint
        run: ./gradlew lintKotlin --continue --no-daemon
      - name: Run Tests
        run: |
          ./gradlew testGithubDebugUnitTest --continue --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/test-results

